CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    provider VARCHAR(20) NOT NULL,
    provider_id VARCHAR(100) NOT NULL,
    nickname VARCHAR(40) NOT NULL,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT pk_members PRIMARY KEY (id),
    CONSTRAINT uk_member_provider_provider_id UNIQUE (provider, provider_id)
);
